// Mock skin data — shape matches raw_json/*.json in the real repo
const RARITY = {
  'Consumer Grade':   { color: '#B0C3D9', bg: '#2a3340' },
  'Industrial Grade': { color: '#5E98D9', bg: '#1f2c43' },
  'Mil-Spec':         { color: '#4B69FF', bg: '#1d2344' },
  'Restricted':       { color: '#8847FF', bg: '#2a1e40' },
  'Classified':       { color: '#D32CE6', bg: '#3a1940' },
  'Covert':           { color: '#EB4B4B', bg: '#3d1f20' },
  'Contraband':       { color: '#E4AE39', bg: '#3a2d16' },
};

// Generate gradient "thumbnails" deterministically per skin — stands in for real webm frames
function skinGradient(seed, a, b, c) {
  return `linear-gradient(${seed % 360}deg, ${a} 0%, ${b} ${35 + (seed%20)}%, ${c} 100%)`;
}

const SKINS = [
  { name:'AK-47 | Asiimov', weapon:'AK-47', rarity:'Covert', collection:'The Danger Zone Collection',
    tags:['sci-fi','orange','black','white','angles','geometry'],
    color:'#253347', grad:'#253347' },
  { name:'AK-47 | Redline', weapon:'AK-47', rarity:'Classified', collection:'The Phoenix Collection',
    tags:['stripes','red','black','minimal'],
    color:'#253347', grad:'#253347' },
  { name:'AK-47 | Neon Rider', weapon:'AK-47', rarity:'Covert', collection:'The Horizon Collection',
    tags:['neon','pink','cyan','japan','streetart'],
    color:'#253347', grad:'#253347' },
  { name:'AK-47 | Bloodsport', weapon:'AK-47', rarity:'Covert', collection:'The Spectrum Collection',
    tags:['red','racing','white','logo'],
    color:'#253347', grad:'#253347' },
  { name:'AK-47 | Vulcan', weapon:'AK-47', rarity:'Covert', collection:'The Huntsman Collection',
    tags:['white','orange','racing','tech'],
    color:'#253347', grad:'#253347' },
  { name:'AWP | Dragon Lore', weapon:'AWP', rarity:'Covert', collection:'The Cobblestone Collection',
    tags:['dragon','gold','green','ornate'],
    color:'#253347', grad:'#253347' },
  { name:'AWP | Asiimov', weapon:'AWP', rarity:'Covert', collection:'The Chroma 2 Collection',
    tags:['sci-fi','orange','black','white','angles'],
    color:'#253347', grad:'#253347' },
  { name:'AWP | Neo-Noir', weapon:'AWP', rarity:'Covert', collection:'The Prisma Collection',
    tags:['purple','pink','femme-fatale','noir'],
    color:'#253347', grad:'#253347' },
  { name:'AWP | Lightning Strike', weapon:'AWP', rarity:'Covert', collection:'The Arms Deal Collection',
    tags:['blue','lightning','black'],
    color:'#253347', grad:'#253347' },
  { name:'AWP | Hyper Beast', weapon:'AWP', rarity:'Covert', collection:'The Chroma 3 Collection',
    tags:['monster','green','cyan','pink','ornate'],
    color:'#253347', grad:'#253347' },
  { name:'M4A4 | Neo-Noir', weapon:'M4A4', rarity:'Covert', collection:'The Clutch Collection',
    tags:['purple','pink','femme-fatale','noir'],
    color:'#253347', grad:'#253347' },
  { name:'M4A4 | Howl', weapon:'M4A4', rarity:'Contraband', collection:'The Huntsman Collection',
    tags:['wolf','red','orange','angry'],
    color:'#253347', grad:'#253347' },
  { name:'M4A1-S | Hot Rod', weapon:'M4A1-S', rarity:'Classified', collection:'The Chroma Collection',
    tags:['red','minimal','chrome','glossy'],
    color:'#253347', grad:'#253347' },
  { name:'M4A1-S | Printstream', weapon:'M4A1-S', rarity:'Covert', collection:'The Snakebite Collection',
    tags:['white','black','minimal','printer'],
    color:'#253347', grad:'#253347' },
  { name:'Desert Eagle | Blaze', weapon:'Desert Eagle', rarity:'Restricted', collection:'The Arms Deal Collection',
    tags:['fire','orange','flames'],
    color:'#253347', grad:'#253347' },
  { name:'USP-S | Kill Confirmed', weapon:'USP-S', rarity:'Covert', collection:'The Shadow Collection',
    tags:['skull','red','white','grunge'],
    color:'#253347', grad:'#253347' },
  { name:'Glock-18 | Fade', weapon:'Glock-18', rarity:'Restricted', collection:'The Arms Deal Collection',
    tags:['fade','pink','yellow','gradient'],
    color:'#253347', grad:'#253347' },
  { name:'Glock-18 | Water Elemental', weapon:'Glock-18', rarity:'Classified', collection:'The Chroma 2 Collection',
    tags:['water','blue','elemental','nature'],
    color:'#253347', grad:'#253347' },
  { name:'P250 | See Ya Later', weapon:'P250', rarity:'Classified', collection:'The Clutch Collection',
    tags:['neon','pink','green','eyes','cartoon'],
    color:'#253347', grad:'#253347' },
  { name:'P90 | Asiimov', weapon:'P90', rarity:'Covert', collection:'The Winter Offensive Collection',
    tags:['sci-fi','orange','black','white','angles'],
    color:'#253347', grad:'#253347' },
  { name:'MP9 | Starlight Protector', weapon:'MP9', rarity:'Covert', collection:'The Prisma 2 Collection',
    tags:['purple','star','girl','anime'],
    color:'#253347', grad:'#253347' },
  { name:'MAC-10 | Neon Rider', weapon:'MAC-10', rarity:'Covert', collection:'The Horizon Collection',
    tags:['neon','pink','cyan','streetart'],
    color:'#253347', grad:'#253347' },
  { name:'UMP-45 | Primal Saber', weapon:'UMP-45', rarity:'Covert', collection:'The Operation Breakout',
    tags:['blue','sword','samurai','pattern'],
    color:'#253347', grad:'#253347' },
  { name:'Nova | Hyper Beast', weapon:'Nova', rarity:'Classified', collection:'The Chroma 3 Collection',
    tags:['monster','green','cyan','pink'],
    color:'#253347', grad:'#253347' },
  { name:'XM1014 | Tranquility', weapon:'XM1014', rarity:'Classified', collection:'The Spectrum Collection',
    tags:['nature','painting','mountain','anime-style'],
    color:'#253347', grad:'#253347' },
];

// Pull out weapon list
const WEAPONS = ['All Weapons', ...new Set(SKINS.map(s => s.weapon)).values()].sort((a,b)=> a==='All Weapons' ? -1 : b==='All Weapons' ? 1 : a.localeCompare(b));

Object.assign(window, { SKINS, RARITY, WEAPONS, skinGradient });
